Repository vmware-tanzu/cloud-suitability-analyzer, pull requests merged in 2020-10, with the labels that each got.

#26 Xpath rules
  go/csa/FileProccesor.go
  go/model/Pattern.go
  rules/config-encryption.yaml
  rules/config-security.yaml
  rules/config-sessionState-xpath.yaml
  rules/config-sessionState.yaml
  rules/dotnet-FileCacheModule.yaml
  rules/dotnet-HttpCacheModule.yaml
  rules/dotnet-ISAPI-Filters-config.yaml
  rules/dotnet-RequestFilteringModule.yaml
  rules/dotnet-StaticCompressionModule.yaml
  rules/dotnet-StaticFileModule.yaml
  rules/dotnet-TokenCacheModule.yaml
  rules/dotnet-UriCacheModule.yaml
  rules/dotnet-WindowsAuth-config.yaml
  rules/dotnet-database-access.yaml
Labels: dco-required

#29 Title: Fix - remove docker non-empty rule
  rules/docker-notEmpty.yaml
Labels: docker, rule

#33 Title: Fix - remove version number from user manual
  doc/CSA-UserManual.md
  doc/CSA-UserManual.pdf
Labels: documentation

#34 non-xml content ignored by XPath rules
  go/model/Pattern.go
Labels: rule, type: bug
